apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  ports: # A service altal elerhatove tett port
    - name: redis
      port: 6379 # A serviceen ezen a porton lesz elerheto
      targetPort: redis # A podnak erre a portjara kerul a forgalom (itt a kontener definiciban hasznalt nev szerepel, lehet szam is)
      protocol: TCP
  selector: # A service mely podok fel tovabbithatja a kereseket
    app.kubernetes.io/name: redis
