apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app.kubernetes.io/name: users
    todosapp.tier: backend
    app.kubernetes.io/instance: {{ .Release.Name }} # Ez uj
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: users
    app.kubernetes.io/instance: {{ .Release.Name }} # Ez uj
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app.kubernetes.io/name: users
    todosapp.tier: backend
    app.kubernetes.io/instance: {{ .Release.Name }} # Ez uj
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: users
      app.kubernetes.io/instance: {{ .Release.Name }} # Ez uj
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users
        todosapp.tier: backend
        app.kubernetes.io/instance: {{ .Release.Name }} # Ez uj
    spec:
      containers:
        - name: users
          image: todoapp/users:{{ .Values.users.tag }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TODOAPP_MongoUrl
              value: "mongodb://mongodb:27017"
            - name: TODOAPP_RedisUrl
              value: "redis"
            - name: TODOAPP_IsDevelopment
              value: "true"
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-api
  labels:
    app.kubernetes.io/name: users-api
    todosapp.tier: backend
    app.kubernetes.io/instance: {{ .Release.Name }} # Ez uj
  annotations:
    traefik.ingress.kubernetes.io/auth-url: http://users/api/auth
    traefik.ingress.kubernetes.io/auth-response-headers: Authorization
    traefik.ingress.kubernetes.io/auth-type: forward
spec:
  rules:
    - http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-auth
  labels:
    app.kubernetes.io/name: users-auth
    todosapp.tier: backend
    app.kubernetes.io/instance: {{ .Release.Name }} # Ez uj
spec:
  rules:
    - http:
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  name: http
